/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 16
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_TAB = 4,
  anon_sym_PIPE = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COMMA = 8,
  sym_list_marker = 9,
  anon_sym_DOT = 10,
  sym_null = 11,
  sym_true = 12,
  sym_false = 13,
  sym_number = 14,
  sym_integer = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_quoted_string_token1 = 17,
  sym_escape_sequence = 18,
  aux_sym_unquoted_string_token1 = 19,
  aux_sym_unquoted_string_token2 = 20,
  aux_sym_unquoted_string_token3 = 21,
  aux_sym_unquoted_string_token4 = 22,
  aux_sym_unquoted_string_token5 = 23,
  aux_sym_unquoted_string_token6 = 24,
  sym_identifier = 25,
  sym__newline = 26,
  sym__newline_indent = 27,
  sym__dedent = 28,
  sym_document = 29,
  sym_object = 30,
  sym_pair = 31,
  sym_array_declaration = 32,
  sym_root_array = 33,
  sym_array_header = 34,
  sym_delimiter_marker = 35,
  sym_field_list = 36,
  sym_field_delimiter = 37,
  sym_field_name = 38,
  sym_inline_values = 39,
  sym_array_content = 40,
  sym_tabular_row = 41,
  sym_list_item = 42,
  sym__inline_value = 43,
  sym_key = 44,
  sym_dotted_key = 45,
  sym_quoted_string = 46,
  sym_unquoted_string = 47,
  sym_delimiter = 48,
  aux_sym_object_repeat1 = 49,
  aux_sym_field_list_repeat1 = 50,
  aux_sym_inline_values_repeat1 = 51,
  aux_sym_array_content_repeat1 = 52,
  aux_sym_array_content_repeat2 = 53,
  aux_sym_dotted_key_repeat1 = 54,
  aux_sym_quoted_string_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_TAB] = "\t",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [sym_list_marker] = "list_marker",
  [anon_sym_DOT] = ".",
  [sym_null] = "null",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_number] = "number",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [aux_sym_unquoted_string_token1] = "unquoted_string_token1",
  [aux_sym_unquoted_string_token2] = "unquoted_string_token2",
  [aux_sym_unquoted_string_token3] = "unquoted_string_token3",
  [aux_sym_unquoted_string_token4] = "unquoted_string_token4",
  [aux_sym_unquoted_string_token5] = "unquoted_string_token5",
  [aux_sym_unquoted_string_token6] = "unquoted_string_token6",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [sym__newline_indent] = "_newline_indent",
  [sym__dedent] = "_dedent",
  [sym_document] = "document",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym_array_declaration] = "array_declaration",
  [sym_root_array] = "root_array",
  [sym_array_header] = "array_header",
  [sym_delimiter_marker] = "delimiter_marker",
  [sym_field_list] = "field_list",
  [sym_field_delimiter] = "field_delimiter",
  [sym_field_name] = "field_name",
  [sym_inline_values] = "inline_values",
  [sym_array_content] = "array_content",
  [sym_tabular_row] = "tabular_row",
  [sym_list_item] = "list_item",
  [sym__inline_value] = "_inline_value",
  [sym_key] = "key",
  [sym_dotted_key] = "dotted_key",
  [sym_quoted_string] = "quoted_string",
  [sym_unquoted_string] = "unquoted_string",
  [sym_delimiter] = "delimiter",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_field_list_repeat1] = "field_list_repeat1",
  [aux_sym_inline_values_repeat1] = "inline_values_repeat1",
  [aux_sym_array_content_repeat1] = "array_content_repeat1",
  [aux_sym_array_content_repeat2] = "array_content_repeat2",
  [aux_sym_dotted_key_repeat1] = "dotted_key_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_list_marker] = sym_list_marker,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_null] = sym_null,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_number] = sym_number,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [aux_sym_unquoted_string_token1] = aux_sym_unquoted_string_token1,
  [aux_sym_unquoted_string_token2] = aux_sym_unquoted_string_token2,
  [aux_sym_unquoted_string_token3] = aux_sym_unquoted_string_token3,
  [aux_sym_unquoted_string_token4] = aux_sym_unquoted_string_token4,
  [aux_sym_unquoted_string_token5] = aux_sym_unquoted_string_token5,
  [aux_sym_unquoted_string_token6] = aux_sym_unquoted_string_token6,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [sym__newline_indent] = sym__newline_indent,
  [sym__dedent] = sym__dedent,
  [sym_document] = sym_document,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym_array_declaration] = sym_array_declaration,
  [sym_root_array] = sym_root_array,
  [sym_array_header] = sym_array_header,
  [sym_delimiter_marker] = sym_delimiter_marker,
  [sym_field_list] = sym_field_list,
  [sym_field_delimiter] = sym_field_delimiter,
  [sym_field_name] = sym_field_name,
  [sym_inline_values] = sym_inline_values,
  [sym_array_content] = sym_array_content,
  [sym_tabular_row] = sym_tabular_row,
  [sym_list_item] = sym_list_item,
  [sym__inline_value] = sym__inline_value,
  [sym_key] = sym_key,
  [sym_dotted_key] = sym_dotted_key,
  [sym_quoted_string] = sym_quoted_string,
  [sym_unquoted_string] = sym_unquoted_string,
  [sym_delimiter] = sym_delimiter,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_field_list_repeat1] = aux_sym_field_list_repeat1,
  [aux_sym_inline_values_repeat1] = aux_sym_inline_values_repeat1,
  [aux_sym_array_content_repeat1] = aux_sym_array_content_repeat1,
  [aux_sym_array_content_repeat2] = aux_sym_array_content_repeat2,
  [aux_sym_dotted_key_repeat1] = aux_sym_dotted_key_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_list_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unquoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unquoted_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unquoted_string_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unquoted_string_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unquoted_string_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unquoted_string_token6] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_root_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_header] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_field_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_values] = {
    .visible = true,
    .named = true,
  },
  [sym_array_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tabular_row] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_value] = {
    .visible = false,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_key] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_values_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_content_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_key_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_delimiter = 2,
  field_fields = 3,
  field_key = 4,
  field_length = 5,
  field_value = 6,
  field_values = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_delimiter] = "delimiter",
  [field_fields] = "fields",
  [field_key] = "key",
  [field_length] = "length",
  [field_value] = "value",
  [field_values] = "values",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 3},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 2},
  [12] = {.index = 17, .length = 1},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
  [15] = {.index = 22, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_length, 1},
  [1] =
    {field_key, 0},
  [2] =
    {field_fields, 3},
    {field_length, 1},
  [4] =
    {field_delimiter, 2},
    {field_length, 1},
  [6] =
    {field_values, 2},
  [7] =
    {field_key, 0},
    {field_value, 2},
  [9] =
    {field_delimiter, 2},
    {field_fields, 4},
    {field_length, 1},
  [12] =
    {field_content, 3},
  [13] =
    {field_key, 0},
    {field_value, 3},
  [15] =
    {field_key, 0},
    {field_values, 3},
  [17] =
    {field_value, 1},
  [18] =
    {field_content, 4},
    {field_key, 0},
  [20] =
    {field_key, 1},
    {field_value, 3},
  [22] =
    {field_key, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = sym_unquoted_string,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 20,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 35,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 51,
  [55] = 53,
  [56] = 41,
  [57] = 35,
  [58] = 41,
  [59] = 35,
  [60] = 41,
  [61] = 35,
  [62] = 41,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 69,
  [73] = 70,
  [74] = 65,
  [75] = 66,
  [76] = 67,
  [77] = 77,
  [78] = 64,
  [79] = 71,
  [80] = 53,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 50,
  [88] = 52,
  [89] = 51,
  [90] = 51,
  [91] = 53,
  [92] = 51,
  [93] = 53,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 113,
  [115] = 98,
  [116] = 116,
  [117] = 111,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 96,
  [122] = 122,
  [123] = 119,
  [124] = 124,
  [125] = 125,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 38,
        ',', 25,
        '-', 27,
        '.', 28,
        ':', 18,
        '@', 14,
        '[', 19,
        '\\', 6,
        ']', 20,
        'f', 48,
        'n', 57,
        't', 54,
        '{', 23,
        '|', 22,
        '}', 24,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(21);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '@') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == 'n') ADVANCE(57);
      if (lookahead == 't') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(45);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 38,
        ',', 25,
        '-', 27,
        '.', 28,
        ':', 18,
        '@', 14,
        '[', 19,
        ']', 20,
        'f', 48,
        'n', 57,
        't', 54,
        '{', 23,
        '|', 22,
        '}', 24,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_list_marker);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_list_marker);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_true);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_false);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token2);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token3);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token4);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_unquoted_string_token6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(55);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(52);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'r') ADVANCE(56);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 's') ADVANCE(50);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(49);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(53);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '+') ||
          ('-' <= lookahead && lookahead <= '/') ||
          (';' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2, .external_lex_state = 2},
  [6] = {.lex_state = 2, .external_lex_state = 2},
  [7] = {.lex_state = 2, .external_lex_state = 3},
  [8] = {.lex_state = 2, .external_lex_state = 2},
  [9] = {.lex_state = 2, .external_lex_state = 3},
  [10] = {.lex_state = 2, .external_lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2, .external_lex_state = 2},
  [13] = {.lex_state = 2, .external_lex_state = 4},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2, .external_lex_state = 3},
  [16] = {.lex_state = 2, .external_lex_state = 3},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 16, .external_lex_state = 3},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16, .external_lex_state = 3},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 1, .external_lex_state = 5},
  [27] = {.lex_state = 1, .external_lex_state = 5},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1, .external_lex_state = 5},
  [32] = {.lex_state = 1, .external_lex_state = 5},
  [33] = {.lex_state = 1, .external_lex_state = 5},
  [34] = {.lex_state = 16, .external_lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 16, .external_lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0, .external_lex_state = 5},
  [45] = {.lex_state = 1, .external_lex_state = 5},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1, .external_lex_state = 5},
  [51] = {.lex_state = 1, .external_lex_state = 5},
  [52] = {.lex_state = 1, .external_lex_state = 5},
  [53] = {.lex_state = 1, .external_lex_state = 5},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 16},
  [70] = {.lex_state = 16},
  [71] = {.lex_state = 16, .external_lex_state = 3},
  [72] = {.lex_state = 16, .external_lex_state = 3},
  [73] = {.lex_state = 16, .external_lex_state = 3},
  [74] = {.lex_state = 16, .external_lex_state = 3},
  [75] = {.lex_state = 16, .external_lex_state = 3},
  [76] = {.lex_state = 16, .external_lex_state = 3},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 16, .external_lex_state = 3},
  [82] = {.lex_state = 16},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 16, .external_lex_state = 3},
  [85] = {.lex_state = 16, .external_lex_state = 3},
  [86] = {.lex_state = 16, .external_lex_state = 3},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0, .external_lex_state = 5},
  [91] = {.lex_state = 0, .external_lex_state = 5},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0, .external_lex_state = 5},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0, .external_lex_state = 3},
  [99] = {.lex_state = 0, .external_lex_state = 3},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0, .external_lex_state = 3},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0, .external_lex_state = 3},
  [105] = {.lex_state = 16},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0, .external_lex_state = 5},
  [110] = {.lex_state = 0, .external_lex_state = 5},
  [111] = {.lex_state = 0, .external_lex_state = 5},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 5},
  [114] = {.lex_state = 0, .external_lex_state = 5},
  [115] = {.lex_state = 0, .external_lex_state = 3},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0, .external_lex_state = 5},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0, .external_lex_state = 3},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 16},
  [125] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_list_marker] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [aux_sym_unquoted_string_token1] = ACTIONS(1),
    [aux_sym_unquoted_string_token2] = ACTIONS(1),
    [aux_sym_unquoted_string_token3] = ACTIONS(1),
    [aux_sym_unquoted_string_token4] = ACTIONS(1),
    [aux_sym_unquoted_string_token5] = ACTIONS(1),
    [aux_sym_unquoted_string_token6] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__newline_indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(120),
    [sym_object] = STATE(101),
    [sym_pair] = STATE(19),
    [sym_array_declaration] = STATE(19),
    [sym_root_array] = STATE(101),
    [sym_array_header] = STATE(112),
    [sym_key] = STATE(64),
    [sym_dotted_key] = STATE(94),
    [sym_quoted_string] = STATE(94),
    [aux_sym_object_repeat1] = STATE(19),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(9), 1,
      sym_list_marker,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(115), 1,
      sym_array_content,
    STATE(7), 2,
      sym_tabular_row,
      aux_sym_array_content_repeat2,
    STATE(38), 2,
      sym_list_item,
      aux_sym_array_content_repeat1,
    STATE(32), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(11), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [42] = 10,
    ACTIONS(9), 1,
      sym_list_marker,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(102), 1,
      sym_array_content,
    STATE(7), 2,
      sym_tabular_row,
      aux_sym_array_content_repeat2,
    STATE(38), 2,
      sym_list_item,
      aux_sym_array_content_repeat1,
    STATE(32), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(11), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [84] = 10,
    ACTIONS(9), 1,
      sym_list_marker,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(98), 1,
      sym_array_content,
    STATE(7), 2,
      sym_tabular_row,
      aux_sym_array_content_repeat2,
    STATE(38), 2,
      sym_list_item,
      aux_sym_array_content_repeat1,
    STATE(32), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(11), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [126] = 9,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      sym__newline,
    ACTIONS(25), 1,
      sym__newline_indent,
    STATE(113), 1,
      sym_inline_values,
    STATE(31), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(21), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [163] = 9,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym__newline,
    ACTIONS(29), 1,
      sym__newline_indent,
    STATE(110), 1,
      sym_inline_values,
    STATE(31), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(21), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [200] = 8,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym__dedent,
    STATE(9), 2,
      sym_tabular_row,
      aux_sym_array_content_repeat2,
    STATE(32), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(11), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [235] = 9,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym__newline,
    ACTIONS(35), 1,
      sym__newline_indent,
    STATE(114), 1,
      sym_inline_values,
    STATE(31), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(21), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [272] = 8,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(52), 1,
      sym__dedent,
    STATE(9), 2,
      sym_tabular_row,
      aux_sym_array_content_repeat2,
    STATE(32), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(37), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(43), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [307] = 8,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(56), 1,
      sym__newline,
    ACTIONS(58), 1,
      sym__newline_indent,
    STATE(117), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(54), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [341] = 9,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(62), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(94), 1,
      sym_dotted_key,
    STATE(95), 1,
      sym_quoted_string,
    STATE(116), 1,
      sym_key,
    STATE(109), 2,
      sym__inline_value,
      sym_unquoted_string,
    ACTIONS(60), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [377] = 8,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(68), 1,
      sym__newline,
    ACTIONS(70), 1,
      sym__newline_indent,
    STATE(111), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(66), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [411] = 7,
    ACTIONS(74), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      sym__newline_indent,
    STATE(83), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(72), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(76), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [442] = 6,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      aux_sym_unquoted_string_token5,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(45), 3,
      sym__inline_value,
      sym_quoted_string,
      sym_unquoted_string,
    ACTIONS(84), 4,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
    ACTIONS(15), 5,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [470] = 2,
    ACTIONS(86), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
      aux_sym_unquoted_string_token5,
      sym_identifier,
    ACTIONS(88), 7,
      sym__dedent,
      anon_sym_DQUOTE,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [488] = 2,
    ACTIONS(90), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
      aux_sym_unquoted_string_token5,
      sym_identifier,
    ACTIONS(92), 7,
      sym__dedent,
      anon_sym_DQUOTE,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [506] = 2,
    ACTIONS(94), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_number,
      aux_sym_unquoted_string_token5,
      sym_identifier,
    ACTIONS(96), 6,
      anon_sym_DQUOTE,
      aux_sym_unquoted_string_token1,
      aux_sym_unquoted_string_token2,
      aux_sym_unquoted_string_token3,
      aux_sym_unquoted_string_token4,
      aux_sym_unquoted_string_token6,
  [523] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(98), 1,
      sym__dedent,
    STATE(78), 1,
      sym_key,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(20), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [545] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_key,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(25), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [567] = 6,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(106), 1,
      sym__dedent,
    STATE(78), 1,
      sym_key,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(20), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [589] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(78), 1,
      sym_key,
    STATE(99), 1,
      sym_object,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(18), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [611] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(78), 1,
      sym_key,
    STATE(104), 1,
      sym_object,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(18), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [633] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(78), 1,
      sym_key,
    STATE(121), 1,
      sym_object,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(18), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [655] = 6,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(78), 1,
      sym_key,
    STATE(96), 1,
      sym_object,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(18), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [677] = 6,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_key,
    STATE(94), 2,
      sym_dotted_key,
      sym_quoted_string,
    STATE(25), 3,
      sym_pair,
      sym_array_declaration,
      aux_sym_object_repeat1,
  [699] = 5,
    ACTIONS(108), 1,
      anon_sym_TAB,
    ACTIONS(112), 1,
      sym__newline,
    STATE(14), 1,
      sym_delimiter,
    STATE(27), 1,
      aux_sym_inline_values_repeat1,
    ACTIONS(110), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [716] = 5,
    ACTIONS(114), 1,
      anon_sym_TAB,
    ACTIONS(120), 1,
      sym__newline,
    STATE(14), 1,
      sym_delimiter,
    STATE(27), 1,
      aux_sym_inline_values_repeat1,
    ACTIONS(117), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [733] = 5,
    ACTIONS(122), 1,
      anon_sym_TAB,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym_field_list_repeat1,
    STATE(46), 1,
      sym_field_delimiter,
    ACTIONS(124), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [750] = 5,
    ACTIONS(128), 1,
      anon_sym_TAB,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym_field_list_repeat1,
    STATE(46), 1,
      sym_field_delimiter,
    ACTIONS(131), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [767] = 5,
    ACTIONS(122), 1,
      anon_sym_TAB,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      aux_sym_field_list_repeat1,
    STATE(46), 1,
      sym_field_delimiter,
    ACTIONS(124), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [784] = 5,
    ACTIONS(108), 1,
      anon_sym_TAB,
    ACTIONS(138), 1,
      sym__newline,
    STATE(14), 1,
      sym_delimiter,
    STATE(26), 1,
      aux_sym_inline_values_repeat1,
    ACTIONS(110), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [801] = 5,
    ACTIONS(108), 1,
      anon_sym_TAB,
    ACTIONS(140), 1,
      sym__newline,
    STATE(14), 1,
      sym_delimiter,
    STATE(33), 1,
      aux_sym_inline_values_repeat1,
    ACTIONS(110), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [818] = 5,
    ACTIONS(108), 1,
      anon_sym_TAB,
    ACTIONS(142), 1,
      sym__newline,
    STATE(14), 1,
      sym_delimiter,
    STATE(27), 1,
      aux_sym_inline_values_repeat1,
    ACTIONS(110), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [835] = 3,
    ACTIONS(144), 1,
      sym_list_marker,
    ACTIONS(147), 1,
      sym__dedent,
    STATE(34), 2,
      sym_list_item,
      aux_sym_array_content_repeat1,
  [846] = 3,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(151), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [857] = 4,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(30), 1,
      sym_field_name,
    STATE(42), 1,
      sym_quoted_string,
  [870] = 4,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    ACTIONS(159), 1,
      anon_sym_TAB,
    ACTIONS(161), 1,
      anon_sym_PIPE,
    STATE(100), 1,
      sym_delimiter_marker,
  [883] = 3,
    ACTIONS(31), 1,
      sym__dedent,
    ACTIONS(163), 1,
      sym_list_marker,
    STATE(34), 2,
      sym_list_item,
      aux_sym_array_content_repeat1,
  [894] = 3,
    ACTIONS(165), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(151), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [905] = 3,
    ACTIONS(169), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(167), 2,
      anon_sym_COLON,
      anon_sym_LBRACK,
  [916] = 3,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(173), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [927] = 2,
    ACTIONS(175), 1,
      anon_sym_TAB,
    ACTIONS(177), 3,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [936] = 3,
    ACTIONS(169), 1,
      anon_sym_DOT,
    STATE(40), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(179), 2,
      anon_sym_COLON,
      anon_sym_LBRACK,
  [947] = 4,
    ACTIONS(169), 1,
      anon_sym_DOT,
    ACTIONS(179), 1,
      anon_sym_COLON,
    ACTIONS(181), 1,
      sym__newline,
    STATE(40), 1,
      aux_sym_dotted_key_repeat1,
  [960] = 2,
    ACTIONS(120), 2,
      sym__newline,
      anon_sym_TAB,
    ACTIONS(183), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [969] = 4,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(42), 1,
      sym_quoted_string,
    STATE(48), 1,
      sym_field_name,
  [982] = 3,
    ACTIONS(185), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(187), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [993] = 2,
    ACTIONS(190), 1,
      anon_sym_TAB,
    ACTIONS(134), 3,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1002] = 3,
    ACTIONS(194), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(192), 2,
      anon_sym_COLON,
      anon_sym_LBRACK,
  [1013] = 2,
    ACTIONS(197), 2,
      sym__newline,
      anon_sym_TAB,
    ACTIONS(199), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1022] = 2,
    ACTIONS(201), 2,
      sym__newline,
      anon_sym_TAB,
    ACTIONS(203), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1031] = 2,
    ACTIONS(181), 2,
      sym__newline,
      anon_sym_TAB,
    ACTIONS(205), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1040] = 2,
    ACTIONS(207), 2,
      sym__newline,
      anon_sym_TAB,
    ACTIONS(209), 2,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [1049] = 2,
    ACTIONS(201), 1,
      anon_sym_TAB,
    ACTIONS(203), 3,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1058] = 2,
    ACTIONS(207), 1,
      anon_sym_TAB,
    ACTIONS(209), 3,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1067] = 3,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(213), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1078] = 3,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(151), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1089] = 3,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(219), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1100] = 3,
    ACTIONS(221), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(151), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1111] = 3,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    STATE(61), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(225), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1122] = 3,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(151), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1133] = 3,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
    STATE(35), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(231), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [1144] = 3,
    ACTIONS(233), 1,
      anon_sym_COLON,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    STATE(103), 1,
      sym_field_list,
  [1154] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(237), 1,
      anon_sym_COLON,
    STATE(119), 1,
      sym_array_header,
  [1164] = 1,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
  [1170] = 1,
    ACTIONS(241), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
  [1176] = 1,
    ACTIONS(243), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
  [1182] = 1,
    ACTIONS(192), 3,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_DOT,
  [1188] = 1,
    ACTIONS(245), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
  [1194] = 1,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
  [1200] = 1,
    ACTIONS(249), 3,
      sym__dedent,
      anon_sym_DQUOTE,
      sym_identifier,
  [1206] = 1,
    ACTIONS(245), 3,
      sym__dedent,
      anon_sym_DQUOTE,
      sym_identifier,
  [1212] = 1,
    ACTIONS(247), 3,
      sym__dedent,
      anon_sym_DQUOTE,
      sym_identifier,
  [1218] = 1,
    ACTIONS(239), 3,
      sym__dedent,
      anon_sym_DQUOTE,
      sym_identifier,
  [1224] = 1,
    ACTIONS(241), 3,
      sym__dedent,
      anon_sym_DQUOTE,
      sym_identifier,
  [1230] = 1,
    ACTIONS(243), 3,
      sym__dedent,
      anon_sym_DQUOTE,
      sym_identifier,
  [1236] = 3,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      anon_sym_COLON,
    STATE(107), 1,
      sym_field_list,
  [1246] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(253), 1,
      anon_sym_COLON,
    STATE(123), 1,
      sym_array_header,
  [1256] = 1,
    ACTIONS(249), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      sym_identifier,
  [1262] = 1,
    ACTIONS(207), 2,
      anon_sym_COLON,
      anon_sym_LBRACK,
  [1267] = 1,
    ACTIONS(255), 2,
      sym__dedent,
      sym_list_marker,
  [1272] = 1,
    ACTIONS(257), 2,
      anon_sym_DQUOTE,
      sym_identifier,
  [1277] = 2,
    ACTIONS(259), 1,
      sym__newline,
    ACTIONS(261), 1,
      sym__newline_indent,
  [1284] = 1,
    ACTIONS(263), 2,
      sym__dedent,
      sym_list_marker,
  [1289] = 1,
    ACTIONS(265), 2,
      sym__dedent,
      sym_list_marker,
  [1294] = 1,
    ACTIONS(267), 2,
      sym__dedent,
      sym_list_marker,
  [1299] = 1,
    ACTIONS(197), 2,
      sym__newline,
      sym__newline_indent,
  [1304] = 1,
    ACTIONS(181), 2,
      sym__newline,
      sym__newline_indent,
  [1309] = 1,
    ACTIONS(201), 2,
      anon_sym_COLON,
      anon_sym_LBRACK,
  [1314] = 1,
    ACTIONS(201), 2,
      sym__newline,
      anon_sym_COLON,
  [1319] = 1,
    ACTIONS(207), 2,
      sym__newline,
      anon_sym_COLON,
  [1324] = 1,
    ACTIONS(201), 2,
      sym__newline,
      sym__newline_indent,
  [1329] = 1,
    ACTIONS(207), 2,
      sym__newline,
      sym__newline_indent,
  [1334] = 1,
    ACTIONS(179), 2,
      anon_sym_COLON,
      anon_sym_LBRACK,
  [1339] = 2,
    ACTIONS(179), 1,
      anon_sym_COLON,
    ACTIONS(269), 1,
      sym__newline,
  [1346] = 1,
    ACTIONS(271), 1,
      sym__dedent,
  [1350] = 1,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
  [1354] = 1,
    ACTIONS(275), 1,
      sym__dedent,
  [1358] = 1,
    ACTIONS(277), 1,
      sym__dedent,
  [1362] = 1,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
  [1366] = 1,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [1370] = 1,
    ACTIONS(283), 1,
      sym__dedent,
  [1374] = 1,
    ACTIONS(285), 1,
      anon_sym_COLON,
  [1378] = 1,
    ACTIONS(287), 1,
      sym__dedent,
  [1382] = 1,
    ACTIONS(289), 1,
      sym_integer,
  [1386] = 1,
    ACTIONS(291), 1,
      anon_sym_COLON,
  [1390] = 1,
    ACTIONS(293), 1,
      anon_sym_COLON,
  [1394] = 1,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [1398] = 1,
    ACTIONS(297), 1,
      sym__newline,
  [1402] = 1,
    ACTIONS(299), 1,
      sym__newline,
  [1406] = 1,
    ACTIONS(301), 1,
      sym__newline,
  [1410] = 1,
    ACTIONS(303), 1,
      anon_sym_COLON,
  [1414] = 1,
    ACTIONS(305), 1,
      sym__newline,
  [1418] = 1,
    ACTIONS(307), 1,
      sym__newline,
  [1422] = 1,
    ACTIONS(309), 1,
      sym__dedent,
  [1426] = 1,
    ACTIONS(311), 1,
      anon_sym_COLON,
  [1430] = 1,
    ACTIONS(313), 1,
      sym__newline,
  [1434] = 1,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
  [1438] = 1,
    ACTIONS(317), 1,
      anon_sym_COLON,
  [1442] = 1,
    ACTIONS(319), 1,
      ts_builtin_sym_end,
  [1446] = 1,
    ACTIONS(321), 1,
      sym__dedent,
  [1450] = 1,
    ACTIONS(323), 1,
      anon_sym_COLON,
  [1454] = 1,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [1458] = 1,
    ACTIONS(327), 1,
      sym_identifier,
  [1462] = 1,
    ACTIONS(329), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 163,
  [SMALL_STATE(7)] = 200,
  [SMALL_STATE(8)] = 235,
  [SMALL_STATE(9)] = 272,
  [SMALL_STATE(10)] = 307,
  [SMALL_STATE(11)] = 341,
  [SMALL_STATE(12)] = 377,
  [SMALL_STATE(13)] = 411,
  [SMALL_STATE(14)] = 442,
  [SMALL_STATE(15)] = 470,
  [SMALL_STATE(16)] = 488,
  [SMALL_STATE(17)] = 506,
  [SMALL_STATE(18)] = 523,
  [SMALL_STATE(19)] = 545,
  [SMALL_STATE(20)] = 567,
  [SMALL_STATE(21)] = 589,
  [SMALL_STATE(22)] = 611,
  [SMALL_STATE(23)] = 633,
  [SMALL_STATE(24)] = 655,
  [SMALL_STATE(25)] = 677,
  [SMALL_STATE(26)] = 699,
  [SMALL_STATE(27)] = 716,
  [SMALL_STATE(28)] = 733,
  [SMALL_STATE(29)] = 750,
  [SMALL_STATE(30)] = 767,
  [SMALL_STATE(31)] = 784,
  [SMALL_STATE(32)] = 801,
  [SMALL_STATE(33)] = 818,
  [SMALL_STATE(34)] = 835,
  [SMALL_STATE(35)] = 846,
  [SMALL_STATE(36)] = 857,
  [SMALL_STATE(37)] = 870,
  [SMALL_STATE(38)] = 883,
  [SMALL_STATE(39)] = 894,
  [SMALL_STATE(40)] = 905,
  [SMALL_STATE(41)] = 916,
  [SMALL_STATE(42)] = 927,
  [SMALL_STATE(43)] = 936,
  [SMALL_STATE(44)] = 947,
  [SMALL_STATE(45)] = 960,
  [SMALL_STATE(46)] = 969,
  [SMALL_STATE(47)] = 982,
  [SMALL_STATE(48)] = 993,
  [SMALL_STATE(49)] = 1002,
  [SMALL_STATE(50)] = 1013,
  [SMALL_STATE(51)] = 1022,
  [SMALL_STATE(52)] = 1031,
  [SMALL_STATE(53)] = 1040,
  [SMALL_STATE(54)] = 1049,
  [SMALL_STATE(55)] = 1058,
  [SMALL_STATE(56)] = 1067,
  [SMALL_STATE(57)] = 1078,
  [SMALL_STATE(58)] = 1089,
  [SMALL_STATE(59)] = 1100,
  [SMALL_STATE(60)] = 1111,
  [SMALL_STATE(61)] = 1122,
  [SMALL_STATE(62)] = 1133,
  [SMALL_STATE(63)] = 1144,
  [SMALL_STATE(64)] = 1154,
  [SMALL_STATE(65)] = 1164,
  [SMALL_STATE(66)] = 1170,
  [SMALL_STATE(67)] = 1176,
  [SMALL_STATE(68)] = 1182,
  [SMALL_STATE(69)] = 1188,
  [SMALL_STATE(70)] = 1194,
  [SMALL_STATE(71)] = 1200,
  [SMALL_STATE(72)] = 1206,
  [SMALL_STATE(73)] = 1212,
  [SMALL_STATE(74)] = 1218,
  [SMALL_STATE(75)] = 1224,
  [SMALL_STATE(76)] = 1230,
  [SMALL_STATE(77)] = 1236,
  [SMALL_STATE(78)] = 1246,
  [SMALL_STATE(79)] = 1256,
  [SMALL_STATE(80)] = 1262,
  [SMALL_STATE(81)] = 1267,
  [SMALL_STATE(82)] = 1272,
  [SMALL_STATE(83)] = 1277,
  [SMALL_STATE(84)] = 1284,
  [SMALL_STATE(85)] = 1289,
  [SMALL_STATE(86)] = 1294,
  [SMALL_STATE(87)] = 1299,
  [SMALL_STATE(88)] = 1304,
  [SMALL_STATE(89)] = 1309,
  [SMALL_STATE(90)] = 1314,
  [SMALL_STATE(91)] = 1319,
  [SMALL_STATE(92)] = 1324,
  [SMALL_STATE(93)] = 1329,
  [SMALL_STATE(94)] = 1334,
  [SMALL_STATE(95)] = 1339,
  [SMALL_STATE(96)] = 1346,
  [SMALL_STATE(97)] = 1350,
  [SMALL_STATE(98)] = 1354,
  [SMALL_STATE(99)] = 1358,
  [SMALL_STATE(100)] = 1362,
  [SMALL_STATE(101)] = 1366,
  [SMALL_STATE(102)] = 1370,
  [SMALL_STATE(103)] = 1374,
  [SMALL_STATE(104)] = 1378,
  [SMALL_STATE(105)] = 1382,
  [SMALL_STATE(106)] = 1386,
  [SMALL_STATE(107)] = 1390,
  [SMALL_STATE(108)] = 1394,
  [SMALL_STATE(109)] = 1398,
  [SMALL_STATE(110)] = 1402,
  [SMALL_STATE(111)] = 1406,
  [SMALL_STATE(112)] = 1410,
  [SMALL_STATE(113)] = 1414,
  [SMALL_STATE(114)] = 1418,
  [SMALL_STATE(115)] = 1422,
  [SMALL_STATE(116)] = 1426,
  [SMALL_STATE(117)] = 1430,
  [SMALL_STATE(118)] = 1434,
  [SMALL_STATE(119)] = 1438,
  [SMALL_STATE(120)] = 1442,
  [SMALL_STATE(121)] = 1446,
  [SMALL_STATE(122)] = 1450,
  [SMALL_STATE(123)] = 1454,
  [SMALL_STATE(124)] = 1458,
  [SMALL_STATE(125)] = 1462,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_content, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_content_repeat2, 2, 0, 0), SHIFT_REPEAT(32),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_content_repeat2, 2, 0, 0), SHIFT_REPEAT(56),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_content_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_content_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_content_repeat2, 2, 0, 0), SHIFT_REPEAT(52),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_content_repeat2, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_row, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_row, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tabular_row, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tabular_row, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimiter, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimiter, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_values, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_values_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_values_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_values_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_list_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_list_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_list_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_values, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_content_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_key, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_name, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_value, 1, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_inline_values_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_list_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquoted_string, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquoted_string, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__inline_value, 1, 0, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_header, 4, 0, 5),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 5, 0, 10),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 5, 0, 11),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 6, 0, 13),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 4, 0, 7),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 4, 0, 3),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_header, 3, 0, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3, 0, 12),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_delimiter, 1, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 5, 0, 14),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 6, 0, 15),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 7, 0, 14),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_value, 1, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimiter_marker, 1, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_header, 5, 0, 8),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_list, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_header, 4, 0, 4),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_array, 4, 0, 6),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_array, 5, 0, 9),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [319] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_list, 4, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_array, 3, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__newline_indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__newline_indent] = sym__newline_indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_indent] = true,
  },
  [3] = {
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline_indent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_toon_external_scanner_create(void);
void tree_sitter_toon_external_scanner_destroy(void *);
bool tree_sitter_toon_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_toon_external_scanner_serialize(void *, char *);
void tree_sitter_toon_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_toon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_toon_external_scanner_create,
      tree_sitter_toon_external_scanner_destroy,
      tree_sitter_toon_external_scanner_scan,
      tree_sitter_toon_external_scanner_serialize,
      tree_sitter_toon_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "toon",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 3,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
